const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Behaviors.Physics,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Behaviors.bound,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Fade,
		C3.Plugins.Audio,
		C3.Behaviors.NoSave,
		C3.Plugins.Timeline,
		C3.Plugins.video,
		C3.Plugins.Keyboard.Cnds.OnAnyKeyReleased,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.SubVar,
		C3.ScriptsInEvents.FolhaFase1_Event3_Act5,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.EveryTick,
		C3.ScriptsInEvents.FolhaFase1_Event7_Act3,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.video.Acts.SetVisible,
		C3.Plugins.video.Acts.SetMuted,
		C3.Plugins.video.Cnds.IsVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.video.Acts.Destroy,
		C3.Plugins.Audio.Cnds.IsAnyPlaying,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.ScriptsInEvents.FolhaFinal_Event5_Act5,
		C3.ScriptsInEvents.FolhaFinal_Event13_Act3
	];
};
self.C3_JsPropNameTable = [
	{Âncora: 0},
	{fundo: 0},
	{fundostart: 0},
	{CentrarEm: 0},
	{Plataforma2: 0},
	{Física: 0},
	{jogador: 0},
	{Sólido: 0},
	{ground: 0},
	{Teclado: 0},
	{history: 0},
	{playgame: 0},
	{Mouse: 0},
	{lava: 0},
	{vida: 0},
	{RestritoAoLayout: 0},
	{Senóide: 0},
	{olho: 0},
	{Pontuação: 0},
	{Projétil: 0},
	{DestruirForaDoLayout: 0},
	{ataque: 0},
	{explosão: 0},
	{Vidas: 0},
	{monstro: 0},
	{Esmaecer: 0},
	{morteolho: 0},
	{Áudio: 0},
	{fundogameover: 0},
	{youlose: 0},
	{quadrotexto: 0},
	{ground2: 0},
	{vidaenergia: 0},
	{Sprite7: 0},
	{movingground: 0},
	{NãoSalvar: 0},
	{V: 0},
	{Sprite: 0},
	{banner: 0},
	{youwin: 0},
	{coração: 0},
	{ControladorDaTimeline: 0},
	{jóiavermelha: 0},
	{foguete: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Vídeo2: 0},
	{Pontos: 0},
	{Vida: 0},
	{jóias: 0}
];

self.InstanceType = {
	fundo: class extends self.ITiledBackgroundInstance {},
	fundostart: class extends self.ITiledBackgroundInstance {},
	jogador: class extends self.ISpriteInstance {},
	ground: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	history: class extends self.ISpriteInstance {},
	playgame: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	lava: class extends self.ISpriteInstance {},
	olho: class extends self.ISpriteInstance {},
	Pontuação: class extends self.ITextInstance {},
	ataque: class extends self.ISpriteInstance {},
	explosão: class extends self.ISpriteInstance {},
	monstro: class extends self.ISpriteInstance {},
	morteolho: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	fundogameover: class extends self.ITiledBackgroundInstance {},
	youlose: class extends self.ISpriteInstance {},
	quadrotexto: class extends self.ISpriteInstance {},
	ground2: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	movingground: class extends self.ISpriteInstance {},
	V: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	banner: class extends self.ISpriteInstance {},
	youwin: class extends self.ISpriteInstance {},
	coração: class extends self.ISpriteInstance {},
	ControladorDaTimeline: class extends self.IInstance {},
	jóiavermelha: class extends self.ISpriteInstance {},
	foguete: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Vídeo2: class extends self.IWorldInstance {}
}